# Generated by Django 3.2.4 on 2021-06-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Player name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Yoshi')),
                ('height', models.CharField(max_length=100, verbose_name='Boyi')),
                ('weight', models.CharField(max_length=50, verbose_name='Vazni')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Maoshi')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.club')),
            ],
        ),
    ]
