# Generated by Django 3.2.4 on 2021-06-23 03:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 6, 23, 3, 48, 14, 260640, tzinfo=utc), upload_to='players/', verbose_name='Rasmi'),
            preserve_default=False,
        ),
    ]
